[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.111.0"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
pydantic = {extras = ["email"], version = "^2.7.1"}
pydantic-settings = "^2.2.1"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.30"}
asyncpg = "^0.29.0"
alembic = "^1.13.1"
gunicorn = "^23.0.0"
aiosmtplib = "^3.0.2"
taskiq = "^0.11.11"
taskiq-aio-pika = "^0.4.1"
jinja2 = "^3.1.5"
bcrypt = "4.0.1"
prometheus-fastapi-instrumentator = "^7.1.0"
elasticsearch = {version = ">=8,<9", extras = ["async"]}

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
locust = "^2.37.11"

