"""Добавлены категории и связь с продуктами

Revision ID: c0b136dde882
Revises: 6eb60bb977d9
Create Date: 2025-06-07 13:14:11.496385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c0b136dde882"
down_revision: Union[str, None] = "6eb60bb977d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.add_column(
        "products", sa.Column("category_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_products_category_id_categories"),
        "products",
        "categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_products_category_id_categories"),
        "products",
        type_="foreignkey",
    )
    op.drop_column("products", "category_id")
    op.drop_table("categories")
    # ### end Alembic commands ###
