"""del sku in models products

Revision ID: 2a595c3ac6a9
Revises: 40f24a07cb19
Create Date: 2025-08-20 14:41:05.463229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2a595c3ac6a9"
down_revision: Union[str, None] = "40f24a07cb19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_sku", "products", type_="unique")
    op.drop_column("products", "sku")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("sku", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_products_sku", "products", ["sku"])
    # ### end Alembic commands ###
