"""fix description column type and nullability

Revision ID: b930b924a9ca
Revises: 3b2cd7be4b04
Create Date: 2025-06-02 12:26:45.370454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b930b924a9ca"
down_revision: Union[str, None] = "3b2cd7be4b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "description",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        nullable=True,
    )
    op.drop_index("ix_users_phone_number", table_name="users")
    op.create_index(
        op.f("ix_users_phone_number"), "users", ["phone_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone_number"), table_name="users")
    op.create_index(
        "ix_users_phone_number", "users", ["phone_number"], unique=True
    )
    op.alter_column(
        "products",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
