global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['host.docker.internal:8000']  # если FastAPI на хосте (Windows/Mac)
    # Если FastAPI в контейнере, например "fastapi_app:8000"
